import assert from "node:assert/strict";
import {resolveModelCard,providersOfRole,useSettings} from "../../src/core/stores/settingsStore";
import {estimateCost} from "../../src/core/pricing";
import {runGenWithFallback} from "../../src/core/retry";
import {budgetGate} from "../../src/core/capability/budget";
const data=new Map<string,string>();
Object.defineProperty(globalThis,"document",{value:{documentElement:{setAttribute:()=>{},classList:{toggle:()=>{}},style:{setProperty:()=>{}}}},configurable:true});
Object.defineProperty(globalThis,"localStorage",{value:{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)},configurable:true});
const card=resolveModelCard("image","codex-membership::codex-image");
assert.deepEqual(budgetGate(999,"会员图片",{billing:"subscription"}),{},"会员额度不受 API 金额预算阻挡");
assert.equal(card.protocol,"codex");assert.equal(card.apiKey,"");assert.equal(estimateCost(card.model,{images:2}),0);
assert.equal(providersOfRole("image").filter(p=>p.id==="codex-membership").length,1);
useSettings.getState().setDefault("image","codex-membership::codex-image");
useSettings.getState().importSettings(useSettings.getState().settings);
assert.equal(useSettings.getState().settings.models.defaults.image,"codex-membership::codex-image","默认模型加载迁移不能丢失会员通道");
useSettings.getState().update("retry",{...useSettings.getState().settings.retry,submitMax:3,fallbackImage:"some-paid-provider"});
let calls=0;await assert.rejects(()=>runGenWithFallback("image",card,undefined,async()=>{calls++;throw Error("503 请求超时");}),/503/);assert.equal(calls,1,"会员失败不得重试或改用付费 API");
const stop=new AbortController();stop.abort();await assert.rejects(()=>runGenWithFallback("image",card,stop.signal,async()=>{calls++;return "不应执行";}));assert.equal(calls,1);
console.log("Codex 模型解析、持久化迁移、额度记账、失败不重试与停止检查通过");
