import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {ReactFlowProvider, ReactFlow, Background} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import "../../src/styles/theme.css";
import "../../src/styles/base.css";
import "../../src/modules/canvas/canvas.css";
import "../../src/modules/studio/studio.css";
import {DesignTools} from "../../src/modules/canvas/DesignTools";
import {ThreeDPage} from "../../src/modules/director/ThreeDPage";
import {ImageStudioStation} from "../../src/modules/studio/image/ImageStudioStation";
import {GroupNode} from "../../src/modules/canvas/nodes/GroupNode";
import {ImageNode} from "../../src/modules/canvas/nodes/ImageNode";
import {useBoard} from "../../src/core/stores/boardStore";
import {useDirector} from "../../src/core/stores/directorStore";
import {useSettings} from "../../src/core/stores/settingsStore";
import {useAssets} from "../../src/core/stores/assetStore";
import {createScenePreset} from "../../src/modules/director/threed/scenePresets";
import {uid} from "../../src/core/utils";
if(location.hostname!=="[::1]")throw new Error("验收页仅限独立来源");
document.documentElement.dataset.theme="light";
const fetchOriginal=window.fetch.bind(window);window.fetch=(input,init)=>/^(data:|blob:)/.test(String(input))?fetchOriginal(input,init):Promise.reject(new Error("验收页禁止调用真实服务"));
useSettings.setState(s=>({settings:{...s.settings,models:{...s.settings.models,providers:[]}}}));
useBoard.getState().newBoard();
const c=document.createElement("canvas");c.width=640;c.height=400;const ctx=c.getContext("2d")!;ctx.fillStyle="#f7efe4";ctx.fillRect(0,0,640,400);ctx.fillStyle="#1d594e";ctx.font="bold 64px sans-serif";ctx.fillText("MOMO 展陈",80,160);ctx.fillStyle="#d7b377";ctx.fillRect(80,200,460,12);ctx.fillStyle="#1d594e";ctx.font="24px sans-serif";ctx.fillText("文化与生活 · 测试素材",80,270);
useBoard.getState().addNode("image",{x:0,y:0},{src:c.toDataURL(),status:"done",name:"文化墙样稿"});
await useAssets.getState().collect({src:c.toDataURL(),kind:"image",name:"文化墙样稿"});
const project=useDirector.getState().createProject("qa-finish",useBoard.getState().activeId,"展陈短片验收");useDirector.getState().updateProject(project.id,{threedEntities:createScenePreset("wall",()=>uid(8))});
const nodeTypes={image:ImageNode,group:GroupNode};
function Preview(){const [page,setPage]=useState("3d"),[design,setDesign]=useState(false),nodes=useBoard(s=>s.nodes),p=useDirector(s=>s.projects.find(p=>p.id===project.id))!;
  return <ReactFlowProvider><nav style={{height:46,padding:8,display:"flex",gap:8,background:"var(--panel)"}}><button className="btn sm" onClick={()=>setPage("3d")}>3D 演示</button><button className="btn sm" onClick={()=>setPage("canvas")}>画布演示</button><button className="btn sm" onClick={()=>setPage("image")}>制图演示</button><button className="btn sm" onClick={()=>setDesign(true)}>设计工具</button><button className="btn sm" onClick={()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==="light"?"black":"light";}}>切换主题</button><small>独立测试项目，不连接真实模型</small></nav><main style={{height:"calc(100vh - 46px)",display:"flex"}}>{page==="3d"?<ThreeDPage project={p}/>:page==="image"?<ImageStudioStation project={p}/>:<ReactFlow nodeTypes={nodeTypes} nodes={nodes} edges={[]} onNodesChange={useBoard.getState().onNodesChange} fitView><Background/></ReactFlow>}</main>{design&&<DesignTools onClose={()=>setDesign(false)}/>}</ReactFlowProvider>;
}
createRoot(document.getElementById("root")!).render(<Preview/>);
