import {useAssets} from "../../src/core/stores/assetStore";
import {compileSegmentPrompt} from "../../src/core/directorQueue";
import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {ReactFlowProvider} from "@xyflow/react";
import {useBoard} from "../../src/core/stores/boardStore";
import {useUi} from "../../src/core/stores/uiStore";
import {useSettings} from "../../src/core/stores/settingsStore";
import {useDirector} from "../../src/core/stores/directorStore";
import {PlanarSheetPanel} from "../../src/modules/canvas/PlanarSheetPanel";
import {H3AuthoringPanel} from "../../src/modules/studio/h3/H3AuthoringPanel";
import {AssetLibrary} from "../../src/modules/assets/AssetLibrary";
import {generatePlanarSheet,PLANAR_SHEET_RULES} from "../../src/core/planarSheet";
import {draftEnglishH3,adoptEnglishH3,patchH3Authoring} from "../../src/core/studio/h3Authoring";
import {validateAuthoredH3} from "../../src/core/studio/h3AuthoringCore";
import {abortNode} from "../../src/core/runControl";
import {IcLogo,IcLayers} from "../../src/ui/icons";
import "../../src/styles/theme.css";import "../../src/styles/base.css";import "../../src/modules/canvas/canvas.css";import "../../src/modules/studio/studio.css";
if(location.hostname!=="[::1]")throw Error("仅允许独立验收来源");
document.documentElement.dataset.theme="black";
const native=window.fetch.bind(window);window.confirm=()=>true;
const c=document.createElement("canvas");c.width=640;c.height=480;const ctx=c.getContext("2d")!;ctx.fillStyle="#fff";ctx.fillRect(0,0,640,480);ctx.fillStyle="#246455";ctx.fillRect(40,50,190,320);ctx.fillStyle="#d6b753";ctx.beginPath();ctx.arc(425,200,110,0,Math.PI*2);ctx.fill();const fixture=c.toDataURL();
const settings=useSettings.getState().settings;useSettings.setState({settings:{...settings,models:{...settings.models,providers:[{id:"qa",name:"模拟模型",baseUrl:"https://qa.invalid/v1",apiKey:"",models:{chat:{protocol:"openai",models:["gpt-4o"]},image:{protocol:"openai",models:["gpt-image-1"]},video:{protocol:"openai",models:[]},audio:{protocol:"openai",models:[]},asr:{protocol:"openai",models:[]}}}],defaults:{chat:"qa::gpt-4o",image:"qa::gpt-image-1"}},budget:{dailyCap:0,perRunCap:0,confirmOverCost:0}}});
useBoard.getState().newBoard();const sourceId=useBoard.getState().addNode("image",{x:0,y:0},{src:fixture,name:"效果图测试参考",status:"done"});
const project=useDirector.getState().createProject("qa-follow",useBoard.getState().activeId,"双语验收");useDirector.getState().updateProject(project.id,{scenes:[{id:"sc",name:"场景",segments:[{id:"seg",sceneId:"sc",summary:"女孩向观众挥手",durationSec:4,dialogue:["你好"],shots:[],h3Authoring:{zh:"女孩向观众挥手，<d>你好</d>。",rules:""}}]} as any]});
useUi.setState({directorProjectId:project.id});
const zh="integrated_multimodal_description:\n[0.00s-4.00s] 女孩挥手。(S1) <d>[Chinese]你好</d>\noverall_soundscape:\n安静的房间。\nnon_diegetic_music:\n无。";
const en="integrated_multimodal_description:\n[0.00s-4.00s] A girl waves. (S1) <d>[Chinese]你好</d>\noverall_soundscape:\nQuiet room.\nnon_diegetic_music:\nNone.";
let reply={zh,en},hold=false,release:(()=>void)|undefined,imageCalls=0,reference=false;
window.fetch=async(input,init)=>{const url=String(input);if(/^(data:|blob:)/.test(url))return native(input,init);if(!url.startsWith("https://qa.invalid/"))throw Error("阻断真实网络："+url);if(hold)await new Promise<void>(r=>release=r);if(url.includes("/images/")){imageCalls++;reference=init?.body instanceof FormData&&[...init.body.keys()].some(k=>k.startsWith("image"));return Response.json({data:[{b64_json:fixture}]});}if(url.includes("chat/completions"))return new Response(`data: ${JSON.stringify({choices:[{delta:{content:JSON.stringify(reply)}}]})}\n\ndata: [DONE]\n\n`,{headers:{"content-type":"text/event-stream"}});throw Error("未定义模拟");};
const check=(x:unknown,m:string)=>{if(!x)throw Error(m);},segment=()=>useDirector.getState().getById(project.id)!.scenes[0].segments[0];
const delay=()=>new Promise(r=>setTimeout(r,30));
function App(){const [log,setLog]=useState(""),[page,setPage]=useState("h3"),[running,setRunning]=useState(false),planar=useUi(s=>s.planarSheetNodeId),p=useDirector(s=>s.getById(project.id))!;
 const test=async(name:string,fn:()=>Promise<void>|void)=>{try{await fn();setLog(s=>s+"通过 · "+name+"\n");}catch(e){setLog(s=>s+"失败 · "+name+" "+String(e)+"\n");}};
 const run=async()=>{setLog("");setRunning(true);
  await test("单张平面总稿独立落画布，带真实源图参考与溯源",async()=>{const id=await generatePlanarSheet(sourceId,PLANAR_SHEET_RULES,"qa::gpt-image-1",1024,1024);check(id&&id!==sourceId&&reference&&imageCalls===1,"源图未传或单张未生成");const n=useBoard.getState().nodes.find(n=>n.id===id);check((n?.data as any).planarSheet.sourceNodeId===sourceId,"溯源丢失");useBoard.getState().spawnEdit(id!,"vectorize");check(useBoard.getState().edges.some(e=>e.source===id&&useBoard.getState().nodes.find(n=>n.id===e.target)?.type==="vectorize"),"矢量错误连接效果图");});
  await test("中英待审与采用分离，采用后对白原文保留",async()=>{await draftEnglishH3(project.id,"seg",new AbortController().signal);check(!segment().promptOverride&&segment().h3Authoring?.enDraft===en,"待审稿提前执行");await adoptEnglishH3(project.id,"seg");check(segment().promptOverride===en&&segment().h3Prompt?.zh?.promptBody===zh,"中英未写入");const p=useDirector.getState().getById(project.id)!;check(compileSegmentPrompt({...p,ruleSet:{...p.ruleSet,positive:{...p.ruleSet?.positive,style:"不要污染执行稿"}}},segment(),"video-t2v").prompt===en,"Base 执行稿被追加风格");});
  await test("错误对白和不存在的参考不能标同步",()=>{const errors=validateAuthoredH3(zh,en.replace("你好","Hello")+" <Picture 7>","t2v",["你好"],{Picture:0,Video:0,Audio:0},4);check(errors.some(s=>s.includes("对白"))&&errors.some(s=>s.includes("不存在")),"校验漏报");});
  await test("时间轴超长及断点拦截",()=>{check(validateAuthoredH3(zh,en.replace("4.00s","9.00s"),"t2v",["你好"],{Picture:0,Video:0,Audio:0},4).some(p=>p.includes("时间")),"时长错误未拦截");});
  await test("英文锁定时保留待审稿，不能覆盖锁稿",async()=>{await draftEnglishH3(project.id,"seg",new AbortController().signal);patchH3Authoring(project.id,"seg",{locks:{executionEn:true,reviewZh:false,structure:false}});let stopped=false;try{await adoptEnglishH3(project.id,"seg");}catch{stopped=true;}check(stopped&&segment().promptOverride===en,"锁失效");patchH3Authoring(project.id,"seg",{locks:{executionEn:false,reviewZh:false,structure:false}});});
  await test("迟到翻译不覆盖期间修改的中文",async()=>{hold=true;release=undefined;const pending=draftEnglishH3(project.id,"seg",new AbortController().signal).then(()=>false,()=>true);for(let i=0;i<100&&!release;i++)await delay();check(release,"未进入模拟请求");patchH3Authoring(project.id,"seg",{h3Authoring:{zh:"新的文案",rules:""}});hold=false;release!();check(await pending,"迟到稿覆盖新输入");check(!segment().h3Authoring?.enDraft,"过期草稿残留");});
  await test("总稿停止后迟到结果不插入画布",async()=>{hold=true;release=undefined;const before=useBoard.getState().nodes.length;const pending=generatePlanarSheet(sourceId,PLANAR_SHEET_RULES,"qa::gpt-image-1",1024,1024).catch(()=>null);for(let i=0;i<100&&!release;i++)await delay();abortNode(`planar-sheet:${sourceId}`);hold=false;release?.();await pending;check(useBoard.getState().nodes.length===before,"停止后仍插入节点");});
  setRunning(false);
 };
 return <ReactFlowProvider><nav style={{display:"flex",gap:12,padding:16}}><IcLogo size={32}/><button className="btn" onClick={()=>useUi.getState().setPlanarSheetNodeId(sourceId)}>平面总稿界面</button><button className="btn" onClick={()=>setPage("h3")}>双语编辑界面</button><button className="btn" onClick={()=>{useAssets.getState().setOpen(true);setPage("assets");}}>资产范围界面</button><button className="btn" disabled={running} onClick={()=>void run()}>运行新流程回归</button><span className="dock-item"><span className="di-ic"><IcLayers/></span></span></nav><pre role="status" style={{padding:16,whiteSpace:"pre-wrap"}}>{log}</pre>{page==="h3"?<main style={{maxWidth:1000,margin:"20px auto"}}><H3AuthoringPanel project={p} seg={p.scenes[0].segments[0]}/></main>:<AssetLibrary/>}{planar&&<PlanarSheetPanel key={planar}/>}</ReactFlowProvider>;
}
createRoot(document.getElementById("root")!).render(<App/>);
