import assert from "node:assert/strict";
import {validateAuthoredH3,isOfficialH3BasePrompt} from "../../src/core/studio/h3AuthoringCore.ts";
const zh="integrated_multimodal_description:\n[0.00s-4.00s] 女孩挥手，<d>[Chinese]你好</d>。\noverall_soundscape:\n房间安静。\nnon_diegetic_music:\n无。";
const en="integrated_multimodal_description:\n[0.00s-4.00s] A girl waves, <d>[Chinese]你好</d>.\noverall_soundscape:\nQuiet room.\nnon_diegetic_music:\nNone.";
const check=(a:string,b:string)=>validateAuthoredH3(a,b,"t2v",["你好"],{Picture:0,Video:0,Audio:0},4);
assert.deepEqual(check(zh,en),[]);
assert(isOfficialH3BasePrompt(en));
assert(!isOfficialH3BasePrompt("Purpose: extra\n"+en));
assert(check(zh,"Purpose: extra\n"+en).some(p=>p.includes("前言")));
assert(check(zh,en.replace("你好","Hello")).some(p=>p.includes("对白")));
assert(check(zh,en+" <Picture 1>").some(p=>p.includes("不存在")));
assert(check(zh,en.replace("4.00s","5.00s")).some(p=>p.includes("时间")));
assert(check(zh,en.replace("0.00s","1.00s")).some(p=>p.includes("覆盖")));
assert(check(zh,en.replace("None.","")).some(p=>p.includes("空小节")));
assert(check(zh,en+"\nnon_diegetic_music:\nNone.").some(p=>p.includes("小节")));
assert(check(zh,zh).some(p=>p.includes("英文描述")));
assert(check(zh,en.replace("[0.00s-4.00s]","[0.00s-2.00s] Camera holds. [2.00s-4.00s]")).some(p=>p.includes("不一致")));
assert.deepEqual(check(zh.replace("房间安静。","[0.00s-4.00s] 房间安静。"),en.replace("Quiet room.","[0.00s-4.00s] Quiet room.")),[]);
console.log("H3 写作合同 13 项通过");
