import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {ReactFlowProvider} from "@xyflow/react";
import "../../src/styles/theme.css";
import "../../src/styles/base.css";
import "../../src/modules/canvas/canvas.css";
import {StudioShell} from "../../src/modules/studio/StudioShell";
import {EcomWorkshop} from "../../src/modules/canvas/nodes/EcomImageNode";
import {useBoard} from "../../src/core/stores/boardStore";
import {useDirector} from "../../src/core/stores/directorStore";
import {useAssets} from "../../src/core/stores/assetStore";
import {parseAuthorTime,parseTimedActions,shouldRelay,selectedDefinitions} from "../../src/core/studio/authoring";
import {effectiveSlots} from "../../src/core/directorRefs";
import {compileSegmentPrompt} from "../../src/core/directorQueue";
import {premiereXml,editingFileUrl} from "../../src/core/studio/editingExportCore";
import {chatCaps} from "../../src/core/modelMeta";
import {eagleRetryDecision,eagleConnectionFailure} from "../../src/core/eagleQueuePolicy";
import type {EcomImageData} from "../../src/core/types";
if(location.hostname!=="[::1]")throw Error("验收只允许独立来源");
document.documentElement.dataset.theme=new URLSearchParams(location.search).get("theme")??"light";
const checks:string[]=[];function check(name:string,ok:boolean){if(!ok)throw Error(name);checks.push(name);}
check("毫秒解析",parseAuthorTime("2500毫秒")===2.5&&parseAuthorTime("01:02.345")===62.345&&parseAuthorTime("1:80")===null);
check("离线及过期登录不丢素材",Array.from({length:100},(_,attempt)=>eagleRetryDecision(false,false,attempt)).every(s=>s==="wait")&&eagleConnectionFailure("Eagle API 校验失败：Token"));
check("恢复连接可继续",eagleRetryDecision(true,true,100)==="done"&&eagleRetryDecision(false,true,0)==="retry");
const shots=parseTimedActions("0.000s-2.500s 阿林推开门\n2.500s-8.000s 她停步回头");
check("时间行识别",shots.length===2&&shots[1].startSec===2.5);
const p=useDirector.getState().createProject("qa-workflow","qa-workflow","夜归 · 分段制作");
useDirector.getState().updateProject(p.id,{script:"# 夜归\n雨夜里，阿林回到熟悉的旧书店。",studioUi:{station:"director"},characters:[{id:"alin",name:"阿林",continuity:"短发，米色外套，深色布包",assetIds:["char-img"]}],assetDefinitions:[{id:"room",kind:"scene",name:"旧书店",description:"暖黄灯，门口有雨水，木质书架",assetIds:["scene-img"]},{id:"bag",kind:"prop",name:"布包",description:"深蓝色帆布包",assetIds:[]}],scenes:[{id:"scene",location:"旧书店",segments:[{id:"one",sceneId:"scene",summary:"雨夜归来",durationSec:8,dialogue:[],shots,characterIds:["alin"],definitionIds:["room"],musicIntent:"none",relayMode:"auto"},{id:"two",sceneId:"scene",summary:"窗边的信",durationSec:8,dialogue:[],shots:[],characterIds:["alin"],definitionIds:["room","bag"],relayMode:"auto"}]}]});
const project=useDirector.getState().getById(p.id)!;
check("按片段素材复用",selectedDefinitions(project,project.scenes[0].segments[0]).includes("短发")&&effectiveSlots(project,project.scenes[0].segments[0]).length===2);
check("首段不接力、同场接力",!shouldRelay(project,project.scenes[0].segments[0])&&shouldRelay(project,project.scenes[0].segments[1]));
check("实际提示词含定义和时间",compileSegmentPrompt(project,project.scenes[0].segments[0],"video-t2v").prompt.includes("2.500s")&&compileSegmentPrompt(project,project.scenes[0].segments[0],"video-t2v").prompt.includes("短发"));
check("Codex 视觉能力",chatCaps({id:"codex-membership",protocol:"codex",model:"codex-chat"}).vision);
const exportXml=premiereXml({clips:[{path:"C:/素材/蓝色 & #1.mp4",inSec:.5,outSec:2.5,durSec:2,volume:1,muted:false}],audio:[{path:"C:/素材/音乐.wav",atSec:.75,volume:.5,muted:false}],titles:[],srt:"",width:1920,height:1080,fps:30,fit:"contain",totalSec:2,assetCount:2},"测试 & 工程",{"C:/素材/音乐.wav":8});
check("PR XML 入出点",exportXml.includes("<in>15</in>")&&exportXml.includes("<out>75</out>")&&exportXml.includes("%23"));
check("PR XML 可解析",!new DOMParser().parseFromString(exportXml,"text/xml").querySelector("parsererror"));
check("文件路径编码",editingFileUrl("C:\\甲 乙\\#a.mp4").endsWith("%23a.mp4"));
useAssets.setState({items:[]});
const nodeId=useBoard.getState().addNode("ecomImage",{x:0,y:0},{slides:Array.from({length:6},(_,i)=>({title:["开场 · 雨夜归来","承启 · 灯下旧书","转折 · 窗边的信"][i%3],prompt:"水墨插画风格，暖色灯光映在书页上；人物位于画面右侧，留白呈现标题。".repeat(12),copy:"每个故事，都值得被看见。"})),status:"idle"});
function App(){const [view,setView]=useState("studio");const current=useDirector(s=>s.projects.find(x=>x.id===p.id)!);const data=useBoard(s=>s.nodes.find(n=>n.id===nodeId)!.data as EcomImageData);return <><nav style={{position:"fixed",bottom:4,left:8,zIndex:1800,background:"var(--panel-solid)",padding:8,display:"flex",gap:10}}><button onClick={()=>setView("studio")}>流程验收</button><button onClick={()=>setView("slices")}>切片验收</button><output>{checks.length} 项断言通过</output></nav><ReactFlowProvider>{view==="studio"?<StudioShell project={current}/>:<EcomWorkshop id={nodeId} d={data} onClose={()=>setView("studio")}/>}</ReactFlowProvider></>}
createRoot(document.getElementById("root")!).render(<App/>);
