import { useEffect, useRef, useState } from "react";
import { cropByRect } from "../../core/maskCanvas";
import type { ElementItem } from "../../core/elementSplit";
import { productionRun } from "../../core/productionTools";
import { errMsg } from "../../core/utils";

/** 人工前景/背景标记与像素蒙版预览，确认后才用于图层导出。 */
export function PrecisionCutout({src,item,onSave,onClose}:{src:string;item:ElementItem;onSave:(png:string)=>void;onClose:()=>void}) {
  const [crop,setCrop]=useState(""),[result,setResult]=useState(item.cutout??""),[keep,setKeep]=useState(true),[brush,setBrush]=useState(18),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const canvas=useRef<HTMLCanvasElement>(null),ctrl=useRef<AbortController|null>(null),last=useRef<[number,number]|null>(null);
  useEffect(()=>{let live=true;void cropByRect(src,{x:item.box[0],y:item.box[1],w:item.box[2],h:item.box[3]}).then(c=>{if(live){setCrop(c.dataUrl);const el=canvas.current;if(el){el.width=c.w;el.height=c.h;}}}).catch(e=>{if(live)setError(errMsg(e));});return()=>{live=false;ctrl.current?.abort();};},[src,item.id]);
  const draw=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(!last.current||busy)return;const el=event.currentTarget,r=el.getBoundingClientRect(),p:[number,number]=[(event.clientX-r.left)*el.width/r.width,(event.clientY-r.top)*el.height/r.height],ctx=el.getContext("2d")!;ctx.strokeStyle=keep?"#00ff00":"#ff0000";ctx.lineWidth=brush*el.width/r.width;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(...last.current);ctx.lineTo(...p);ctx.stroke();last.current=p;};
  const run=async(op:"segment"|"semantic")=>{if(!crop||ctrl.current)return;const c=new AbortController();ctrl.current=c;setBusy(true);setError("");try{const v=await productionRun<{png:string}>({op,image:crop,initial:result||undefined,marks:canvas.current?.toDataURL()},c.signal);c.signal.throwIfAborted();setResult(v.png);}catch(e){setError(errMsg(e));}finally{ctrl.current=null;setBusy(false);}};
  return <div className="design-overlay" style={{zIndex:1500}}><section className="design-dialog" role="dialog" aria-modal="true" aria-label="精细蒙版"><header><b>精细蒙版 · {item.name}</b><button className="btn sm" onClick={onClose}>关闭</button></header>
    <p>绿色涂要保留的主体，红色涂要删除的背景；计算后检查右侧，再应用。保留原始 RGB，只修改透明度。</p><div style={{display:"flex",gap:8}}><button className={`btn ${keep?"primary":""}`} onClick={()=>setKeep(true)}>保留笔</button><button className={`btn ${!keep?"primary":""}`} onClick={()=>setKeep(false)}>删除笔</button><label>笔刷<input type="range" min={2} max={80} value={brush} onChange={e=>setBrush(+e.target.value)}/></label><button className="btn" disabled={busy} onClick={()=>{const el=canvas.current;el?.getContext("2d")?.clearRect(0,0,el.width,el.height);}}>清除标记</button></div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,alignItems:"start"}}><div style={{position:"relative"}}>{crop&&<img src={crop} alt="标记前景和背景" style={{width:"100%",display:"block"}}/>}<canvas ref={canvas} style={{position:"absolute",inset:0,width:"100%",height:"100%",touchAction:"none",cursor:"crosshair"}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();last.current=[(e.clientX-r.left)*e.currentTarget.width/r.width,(e.clientY-r.top)*e.currentTarget.height/r.height];draw(e);}} onPointerMove={draw} onPointerUp={()=>{last.current=null;}} onPointerCancel={()=>{last.current=null;}}/></div><div style={{background:"repeating-conic-gradient(var(--bg) 0 25%,var(--panel) 0 50%) 0/20px 20px"}}>{result&&<img src={result} alt="透明蒙版预览" style={{width:"100%"}}/>}</div></div>
    {error&&<p role="alert">{error}</p>}<footer>{busy?<button className="btn" onClick={()=>ctrl.current?.abort()}>停止计算</button>:<><button className="btn" disabled={!crop} title="首次使用会下载约 5MB 的 U2NetP 主体模型，之后离线运行" onClick={()=>void run("semantic")}>AI 主体蒙版</button><button className="btn" disabled={!crop} onClick={()=>void run("segment")}>按标记精修</button></>}<button className="btn primary" disabled={!result||busy} onClick={()=>{onSave(result);onClose();}}>应用蒙版</button></footer>
  </section></div>;
}
