/**
 * 风格预设库 — 内置提示词片段（中文标签 → 英文片段）
 */
export type StyleEntry = { label: string; value: string; group?: string };

export const STYLE_PRESETS: Record<string, StyleEntry[]> = {
  海报: [
    { group: "版式", label: "瑞士网格", value: "Swiss graphic design poster, strict modular grid, asymmetric typography, generous margins" },
    { group: "版式", label: "杂志封面", value: "editorial magazine cover, strong focal image, clear headline hierarchy, balanced cover lines" },
    { group: "版式", label: "极简留白", value: "minimal poster design, a single visual focus, ample negative space, restrained typography" },
    { group: "版式", label: "大字排版", value: "typographic poster, oversized expressive headline, clear hierarchy, deliberate letter spacing" },
    { group: "版式", label: "对角动势", value: "dynamic diagonal poster composition, directional shapes, energetic visual rhythm" },
    { group: "版式", label: "拼贴版面", value: "editorial collage poster, cutout photographs, paper layers, deliberate visual hierarchy" },
    { group: "商业", label: "产品主视觉", value: "commercial product hero poster, prominent product, controlled studio lighting, space for headline and offer" },
    { group: "商业", label: "美妆质感", value: "premium cosmetics poster, elegant product still life, delicate highlights, refined neutral palette" },
    { group: "商业", label: "美食特写", value: "food advertising poster, appetizing close-up textures, warm lighting, uncluttered headline area" },
    { group: "商业", label: "时尚大片", value: "fashion campaign poster, bold editorial photography, sophisticated art direction, concise typography" },
    { group: "商业", label: "促销活动", value: "retail campaign poster, bold offer hierarchy, contrasting color blocks, readable price area" },
    { group: "商业", label: "科技发布", value: "technology launch poster, precise geometric layout, luminous product accents, clean information hierarchy" },
    { group: "文化", label: "新中式", value: "contemporary Chinese poster design, traditional motifs with modern grid, restrained ink and vermilion accents" },
    { group: "文化", label: "电影叙事", value: "cinematic film poster, atmospheric storytelling, layered depth, dramatic focal subject and title area" },
    { group: "文化", label: "音乐演出", value: "music event poster, expressive visual rhythm, bold headline, orderly date and venue information" },
    { group: "文化", label: "展览图录", value: "art exhibition poster, curatorial editorial layout, ample whitespace, understated type hierarchy" },
    { group: "文化", label: "复古旅行", value: "vintage travel poster, simplified landscape shapes, warm limited palette, screen-print texture" },
    { group: "文化", label: "节日庆典", value: "festive celebration poster, decorative framing, warm joyful palette, clear central message" },
    { group: "实验", label: "包豪斯", value: "Bauhaus poster design, geometric circles and bars, primary colors, balanced asymmetric composition" },
    { group: "实验", label: "酸性设计", value: "acid graphic design poster, distorted chrome accents, fluorescent colors, experimental typography" },
    { group: "实验", label: "Y2K", value: "Y2K poster aesthetic, glossy metallic forms, playful futuristic graphics, vibrant digital palette" },
    { group: "实验", label: "复古印刷", value: "risograph poster, limited spot colors, subtle ink misregistration, tactile recycled paper" },
  ],
  艺术风格: [
    { label: "吉卜力动画", value: "Studio Ghibli style, hand-painted animation" },
    { label: "赛博朋克", value: "cyberpunk, neon lights, futuristic city" },
    { label: "国风水墨", value: "traditional Chinese ink painting, shan shui" },
    { label: "油画厚涂", value: "impasto oil painting, thick brush strokes" },
    { label: "扁平插画", value: "flat vector illustration, minimal shapes" },
    { label: "像素艺术", value: "pixel art, 16-bit retro game style" },
    { label: "水彩", value: "watercolor painting, soft edges, paper texture" },
    { label: "3D 渲染", value: "octane render, 3D, physically based rendering" },
    { label: "黏土定格", value: "claymation, stop motion, plasticine texture" },
    { label: "浮世绘", value: "ukiyo-e, Japanese woodblock print" },
    { label: "蒸汽波", value: "vaporwave aesthetic, retro futurism, pastel gradients" },
    { label: "极简主义", value: "minimalist, negative space, clean composition" },
    { label: "铅笔素描", value: "graphite pencil drawing, controlled hatching, textured drawing paper" },
    { label: "钢笔速写", value: "pen and ink sketch, expressive fine lines, cross hatching" },
    { label: "炭笔人物", value: "charcoal drawing, broad tonal masses, soft smudged shading" },
    { label: "彩铅手绘", value: "colored pencil illustration, layered pencil strokes, soft paper grain" },
    { label: "粉彩绘画", value: "soft pastel painting, velvety pigment, blended luminous colors" },
    { label: "水粉插画", value: "gouache illustration, opaque matte colors, handcrafted brushwork" },
    { label: "丙烯绘画", value: "acrylic painting, saturated opaque colors, visible layered brushwork" },
    { label: "工笔重彩", value: "Chinese gongbi painting, meticulous fine outlines, layered mineral pigments" },
    { label: "版画套色", value: "linocut print, carved bold lines, limited layered spot colors" },
    { label: "剪纸艺术", value: "papercut illustration, crisp cut edges, layered paper silhouettes" },
    { label: "儿童绘本", value: "children's picture book illustration, warm narrative details, playful hand-drawn forms" },
    { label: "美式漫画", value: "comic book illustration, bold ink contours, dramatic shadow blocks, halftone dots" },
    { label: "日系赛璐璐", value: "anime cel shading, clean line art, flat color blocks with sharp shadow boundaries" },
    { label: "低多边形", value: "low-poly 3D illustration, faceted geometry, simple materials" },
    { label: "等距插画", value: "isometric illustration, parallel projection, clean miniature scene" },
    { label: "超现实", value: "surrealist painting, dreamlike juxtapositions, convincing impossible scenes" },
  ],
  光影: [
    { label: "电影布光", value: "cinematic lighting, dramatic shadows" },
    { label: "黄金时刻", value: "golden hour, warm sunlight, long shadows" },
    { label: "霓虹夜景", value: "neon glow, night scene, reflective surfaces" },
    { label: "柔光棚拍", value: "soft studio lighting, diffused light" },
    { label: "逆光剪影", value: "backlight, rim light, silhouette" },
    { label: "体积光", value: "volumetric light, god rays, atmospheric" },
    { label: "烛光暖调", value: "candlelight, warm amber tones, cozy" },
    { label: "冷月清辉", value: "moonlight, cool blue tones, tranquil night" },
  ],
  镜头: [
    { label: "特写", value: "close-up shot, shallow depth of field" },
    { label: "广角全景", value: "wide angle panorama, expansive view" },
    { label: "俯拍航拍", value: "aerial view, drone shot, top-down" },
    { label: "低角度仰拍", value: "low angle shot, towering perspective" },
    { label: "微距", value: "macro photography, extreme detail" },
    { label: "鱼眼", value: "fisheye lens, distorted perspective" },
    { label: "移轴微缩", value: "tilt-shift, miniature effect" },
    { label: "长焦压缩", value: "telephoto compression, bokeh background" },
    { group: "景别", label: "大远景", value: "extreme long shot, subject small within a vast environment" },
    { group: "景别", label: "全身", value: "full shot, entire subject visible with breathing room" },
    { group: "景别", label: "中景", value: "medium shot, waist-up framing, readable body gesture" },
    { group: "景别", label: "近景", value: "medium close-up, chest-up framing, focused expression" },
    { group: "景别", label: "局部细节", value: "extreme close-up, isolated surface detail filling the frame" },
    { group: "视角", label: "平视", value: "eye-level camera angle, natural neutral perspective" },
    { group: "视角", label: "俯视", value: "high-angle view, camera tilted downward toward the subject" },
    { group: "视角", label: "垂直顶视", value: "overhead top-down view, camera pointing vertically downward, flat lay composition" },
    { group: "视角", label: "贴地仰视", value: "worm's-eye view, camera very close to the ground looking upward" },
    { group: "视角", label: "正面", value: "front view, camera directly facing the subject" },
    { group: "视角", label: "侧面", value: "side profile view, camera perpendicular to the subject" },
    { group: "视角", label: "四分之三", value: "three-quarter view, subject viewed from a 45-degree angle" },
    { group: "视角", label: "背面", value: "rear view, camera facing the back of the subject" },
    { group: "视角", label: "过肩", value: "over-the-shoulder shot, foreground shoulder framing the main subject" },
    { group: "视角", label: "主观视角", value: "first-person point-of-view shot, scene from the observer's eye position" },
    { group: "构图", label: "倾斜机位", value: "Dutch angle, intentionally tilted horizon, dramatic tension" },
    { group: "构图", label: "对称居中", value: "centered symmetrical composition, balanced forms on either side" },
    { group: "构图", label: "三分构图", value: "rule of thirds composition, subject placed at a thirds intersection" },
    { group: "构图", label: "前景框景", value: "frame within a frame, foreground shapes guiding attention to the subject" },
    { group: "构图", label: "引导线", value: "leading lines converging toward the subject, strong spatial depth" },
    { group: "光学", label: "标准镜头", value: "50mm standard lens perspective, natural proportions" },
    { group: "光学", label: "广角透视", value: "24mm wide-angle lens, pronounced near-far perspective" },
    { group: "光学", label: "深景深", value: "deep depth of field, foreground and background both in focus" },
    { group: "光学", label: "浅景深", value: "shallow depth of field, selective focus, softly blurred background" },
  ],
  质感: [
    { label: "8K 超清", value: "8K resolution, ultra detailed, sharp focus" },
    { label: "胶片颗粒", value: "film grain, Kodak Portra 400, analog photo" },
    { label: "磨砂玻璃", value: "frosted glass, translucent material" },
    { label: "金属拉丝", value: "brushed metal, metallic reflections" },
    { label: "丝绒织物", value: "velvet fabric, soft plush texture" },
    { label: "湿润反光", value: "wet surface, glossy reflections, rain" },
  ],
  氛围: [
    { label: "梦幻仙境", value: "dreamy, ethereal, fairy tale atmosphere" },
    { label: "史诗宏大", value: "epic scale, grand, awe-inspiring" },
    { label: "静谧治愈", value: "serene, peaceful, healing atmosphere" },
    { label: "神秘暗黑", value: "mysterious, dark fantasy, ominous" },
    { label: "热闹烟火气", value: "lively street, bustling, warm human touch" },
    { label: "孤独苍凉", value: "lonely, desolate, melancholic vast emptiness" },
  ],
  色彩: [
    { label: "莫兰迪低饱和", value: "muted morandi color palette, low saturation" },
    { label: "高饱和撞色", value: "vibrant complementary colors, bold contrast" },
    { label: "黑白灰", value: "monochrome, black and white, grayscale" },
    { label: "马卡龙粉彩", value: "pastel macaron colors, soft and sweet" },
    { label: "青橙电影感", value: "teal and orange color grading, cinematic" },
    { label: "复古暖褐", value: "vintage sepia tones, nostalgic warmth" },
  ],
};

export const STYLE_CATEGORIES = Object.keys(STYLE_PRESETS);
